#ifndef _KARIN_MEDIA_UTIL_H
#define _KARIN_MEDIA_UTIL_H

#define RE3D_MIDI_COUNT 4
#define CT3D_MIDI_COUNT 0
#define EGYPT3D_MIDI_COUNT 6
#define CLONE3D_MIDI_COUNT 3
#define CT3DEP2_MIDI_COUNT 5
#define CT3DEP3_MIDI_COUNT 5
#define SPECNAZ3D_MIDI_COUNT 5

#endif
