######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 17 20:37:54 2016
######################################################################

TEMPLATE = subdirs

SUBDIRS = libnetlizard qnetlizard

CONFIG += ordered
