######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 17 20:37:54 2016
######################################################################

CONFIG += debug_and_release

CONFIG(debug, debug|release) {

DEFINES += _DEV_TEST
BUILD_DIR_NAME = .build.debug

} else {

BUILD_DIR_NAME = .build

}

BUILD_DIR = $$PWD/$$BUILD_DIR_NAME
OBJ_DIR_NAME = obj

unix {
DEFINES += _OS_UNIX
} else:win32 {
DEFINES += _OS_WIN
}
